name: CreateEBS

on:
  workflow_dispatch:
    inputs:
      region:
       description: region
       required: true
       type: string
      volume-size:
       description: Ebs volume-type
       required: true
       type: string
jobs:       
  Create-EBS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}'
          aws-region: ap-south-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform apply
        id:   apply
        env:
          TF_VAR_region:  "${{ github.event.inputs.region}}"
          TE_VAR_volume_size: "${{ github.event.inputs.volume-size}}"
        run: |
          cd tf-ebs/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve