name: 'Terraform-apply'

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: EC2 name
        required: true
        default: ' '
        type: string

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
    - name: Terraform Apply
      id:   apply
      env:
        TF_VAR_instance_name:  "${{ github.event.inputs.instance_name }}"
      run: |
        cd tf-example/
        terraform init
        terraform plan 
        terraform apply -auto-approve