name: Provision t2.micro EC2

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
          terraform_wrapper: false
    - name: Terraform Apply
      id:   apply
      env:
        TF_VAR_instance_name:  "${{ github.event.inputs.instance_name }}"
      run: |
        cd tf-example/
        terraform init
        terraform validate
        terraform plan 
        terraform apply -auto-approve