name: Provision t2.micro EC2

on:
  workflow_dispatch:
    inputs:
      name:
        description: EC2 type
        required: true
        type: choice
        options:
        - t3.micro
        - t3.small
        - t2.nano
        
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Terraform plan
      id:   plan
      env:
        TF_VAR_INPUT_Name: " ${{ github.event.inputs.name }} "
      run: |
        cd tf-example/
        terraform init
        terraform validate -input=false -var-file=${{ TF_VAR_instance_type }}variables.tf -no-color
        terraform plan -input=false -var-file=${{ TF_VAR_instance_type }}variables.tf -no-color
       # terraform apply -var= "instance_type= ${{ github.event.inputs.instance-type }}" -auto-approve